### ISSUE TITLE
_

### ISSUE THREAD

**Issue by ghost** [mupen64plus/mupen64plus-input-sdl#115]
_

**Comment by richard42** [comment]
looks like a bug in the glide64mk2 video plugin

**Comment by briancullinan** [comment]
> looks like a bug in the glide64mk2 video plugin

Ah, yes. Now I see it. Here, I thought I was being clever connecting SDL to inputs.

**Comment by orbea** [comment]
@richard42 Can you close this issue? It was deleted leaving no info and your comment suggests its posted in the wrong repo anyways.
