### ISSUE TITLE
Linux MayFlash Z and Start inverted

### ISSUE THREAD

**Issue by Beanow** [mupen64plus/mupen64plus-input-sdl#44]
The `ID 0079:1879 DragonRise Inc.` MayFlash 2-port controller adapter on Linux has the inverted Start and Z buttons from the autoconfig.

They are listed as `USB GamePad USB GamePad` and work well with:

```ini
AnalogDeadzone = "100,100"
AnalogPeak = "20000,20000"
DPad R = "button(13)"
DPad L = "button(15)"
DPad D = "button(14)"
DPad U = "button(12)"
Start = "button(8)"
Z Trig = "button(9)"
B Button = "button(2)"
A Button = "button(1)"
C Button R = "axis(3-)"
C Button L = "axis(3+)"
C Button D = "axis(2+)"
C Button U = "axis(2-)"
R Trig = "button(7)"
L Trig = "button(6)"
Mempak switch = ""
Rumblepak switch = ""
X Axis = "axis(0-,0+)"
Y Axis = "axis(1-,1+)"
```

(A good tool to verify is `jstest-gtk`)

**Comment by RickSanchez86** [comment]
can confirm this error on windows too. https://github.com/m64p/mupen64plus-GLideN64/issues/47

**Comment by richard42** [comment]
okay, thanks for the info. I just pushed a change to fix this.
