### ISSUE TITLE
Option to Prevent More Than One C-Button Input

### ISSUE THREAD

**Issue by GitSome1648** [mupen64plus/mupen64plus-input-sdl#51]
Since modern controllers only have 4 digital buttons on the right face, the N64 C-buttons are typically mapped to the right analogue stick.  If the right stick is not pressed directly left, right, up, or down, the emulator will often interpret the input as two C-buttons being pressed at the same time.  While this behavior is desirable for some games (like first person shooters that use the C-buttons for movement), it is undesirable for games that expect the player to only press one button at a time, such as Star Fox and the Legend of Zelda.

I would appreciate an option to only allow one C-button input at a time.  When the option is set and the C-buttons are mapped to analogue axises, the emulator would only press the C-button with the highest axis absolute value when multiple axises are activated.  This option would make C-button input more forgiving for those with sloppier thumbs.

**Comment by loganmc10** [comment]
There is actually a little known option to configure the deadzone for button inputs.

So for instance, in mupen64plus.cfg you might have this:

```
C Button D = "axis(1+)"
```
You can also do:
```
C Button D = "axis(1+,10000)"
```

With the "10000" being the deadzone (ie the button press won't register until the axis hits that value). It defaults to 6000. The max (axis is fully extended) is 32768.

By increasing that deadzone, you reduce the risk of hitting 2 buttons at once.

**Comment by GitSome1648** [comment]
Thanks, that helped.  Maybe that option should be described in one of the default comments in mupen64plug.cfg.
