### ISSUE TITLE
Logitech F310 auto configuration issue

### ISSUE THREAD

**Issue by snessy7** [mupen64plus/mupen64plus-input-sdl#81]
Somebody contributed an auto configuration for the Logitech F310 gamepad a few years ago.  The F310 is a fairly common Xbox-like USB gamepad, and I like to use it with emulators on my laptop.  The auto config supplied by mupen64plus-input-sdl (v2.5-4 on my Pop!_OS 19.04 distro) mostly works, except that it maps the L/R bumper buttons to the two analog trigger buttons on the Logitech.  This causes problems in some games, like WCW vs NWO Revenge and Star Wars: Shadows of the Empire.  For example, in SotE you can't get past the save slot/name selection screen, because the L/R buttons (which are constantly being "pressed" due to the mapping) have you constantly selecting the Options dialog and unable to successfully escape by hitting Start in order to start the game.  Some games basically still work, although you might get weird behavior on some screens that use L/R, and I'd imagine there are still more games more severely affected.  In Revenge you cannot select a wrestler because the game is constantly paging through the list due to the bumper buttons both reading a signal.

My solution was to map L/R to the actual physical L/R bumper/shoulder buttons on the Logitech F310 (buttons 4 & 5).  The Z Trigger was mapped to the right shoulder (button 5) for some reason, so I remapped it to the right trigger, although either left or right trigger should be fine.  I had to use some SDL gamepad diagnostic utilities and the SotE game manual to track down what was happening.   Here is my revised controller configuration, and I would recommend you consider replacing your default auto mapping with these settings for the F310.

`# Mupen64Plus SDL Input Plugin config parameter version number.  Please don't change this version number.
version = 2
# Controller configuration mode: 0=Fully Manual, 1=Auto with named SDL Device, 2=Fully automatic
mode = 0
# Specifies which joystick is bound to this controller: -1=No joystick, 0 or more= SDL Joystick number
device = 0
# SDL joystick name (or Keyboard)
name = "Logitech Gamepad F310"
# Specifies whether this controller is 'plugged in' to the simulated N64
plugged = True
# Specifies which type of expansion pak is in the controller: 1=None, 2=Mem pak, 5=Rumble pak
plugin = 2
# If True, then mouse buttons may be used with this controller
mouse = False
# Scaling factor for mouse movements.  For X, Y axes.
MouseSensitivity = "2.00,2.00"
# The minimum absolute value of the SDL analog joystick axis to move the N64 controller axis value from 0.  For X, Y axes.
AnalogDeadzone = "4096,4096"
# An absolute value of the SDL joystick axis >= AnalogPeak will saturate the N64 controller axis value (at 80).  For X, Y axes. For each axis, this must be greater than the corresponding AnalogDeadzone value
AnalogPeak = "32768,32768"
# Digital button configuration mappings
DPad R = "hat(0 Right)"
DPad L = "hat(0 Left)"
DPad D = "hat(0 Down)"
DPad U = "hat(0 Up)"
Start = "button(7)"
Z Trig = "axis(5+)"
#or...
#Z Trig = "axis(2+)"
B Button = "button(2)"
A Button = "button(0)"
C Button R = "axis(3+)"
C Button L = "axis(3-)"
C Button D = "axis(4+)"
C Button U = "axis(4-)"
# UPDATED R/L mapping...
R Trig = "button(5)"
L Trig = "button(4)"
Mempak switch = "button(1)"
Rumblepak switch = "button(3)"
# Analog axis configuration mappings
X Axis = "axis(0-,0+)"
Y Axis = "axis(1-,1+)"`

**Comment by richard42** [comment]
OK thanks, this should be fixed now.
