### ISSUE TITLE
Numpad not working and unhandled exception when binding numpad key 5 with num lock turned off.

### ISSUE THREAD

**Issue by it9exm** [mupen64plus/mupen64plus-input-sdl#84]
Hi,
if I configure number key bindings (I usually do this for c-buttons), they don't actually work when i press the respective keys on the numpad, either with num lock turned on or off. They work only when i press the keys on number strip beneath the F1-F12 keys.
Moreover, if I try to bind the numpad key 5 and num lock is off, the program closes itself with an unhandled exception. 
I am using the latest version of mupen64plus-input-sdl with the latest version of mupen64plus and the m64py gui on Debian Sid.

**Comment by richard42** [comment]
The SDL keycodes for the number keys above the letters are SDLK_0 (48) through SDLK_9 (57).  The keycodes for the numeric keypad digits are SDLK_KP0 (256) through SDLK_KP9 (265).
