### ISSUE TITLE
InputAutoCfg.ini / Wrong Logitech F710 mappings for A and B.

### ISSUE THREAD

**Issue by BrendonIrwan** [mupen64plus/mupen64plus-input-sdl#92]
The (Wireless) F710 has the same button layout as the F310 but the mappings for A and B are different.
It should be as follows:
```
B Button = button(2)
A Button = button(0)
```
The current setting feels like those NEOGEO Mini controllers where the jump and action buttons are at the wrong angle.

**Comment by richard42** [comment]
Thanks, fixed in c0d76df
